models:
  content_expansion:
    model_name: stable-beluga:13b
    api_type: ollama
    temperature: 0.7
    max_tokens: 1024
    top_p: 0.9
  outline_generation:
    model_name: phi3.5:latest
    api_type: ollama
    temperature: 0.5
    max_tokens: 512
    top_p: 0.8
  organization:
    model_name: deepseek-r1:8b
    api_type: ollama
    temperature: 0.4
    max_tokens: 512
    top_p: 0.8
ollama:
  base_url: http://192.168.31.157:11434
